<?php


namespace App\Repositories;


use App\Models\GroupHotel;
use Ramsey\Uuid\Uuid;

class GroupHotelRepository extends RepositoryAbstract
{

    public function __construct(GroupHotel $model)
    {
        parent::__construct($model);
    }

    protected $fieldFilters = [
        'name' => ['name', 'scope' => 'byName']
    ];
    public function create(array $data)
    {
        $data['uuid'] = Uuid::uuid4()->toString();
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
