<?php

namespace App\Repositories;

use App\Models\Hotel;
use Illuminate\Support\Arr;
use Ramsey\Uuid\Uuid;

class HotelRepository extends RepositoryAbstract
{

    public function __construct(Hotel $model)
    {
        parent::__construct($model);
    }

    protected $fieldFilters = [
        'name' => ['field' =>'name', 'scope' => 'byName'],
        'city' => ['field' =>'city', 'scope' => 'byCity'],
        'address' => ['field' =>'address', 'scope' => 'byAddress'],
        'starts' => ['field' =>'starts', 'scope' => 'byStarts'],
        'search' => ['field' =>'search', 'scope' => 'bySearch'],
    ];

    public function create(array $data)
    {
        $data['uuid'] = Uuid::uuid4()->toString();
        if (is_null(Arr::get($data, 'image'))) {
            $data['image']= 'images/nologo.jpeg';
        }
        return parent::create($data); // TODO: Change the autogenerated stub
    }
}
